version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
        - ./:/var/www
        - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
        - "8876:80"
        depends_on:
        - app
        container_name: news_nginx

    app:
        build:
          context: .
          dockerfile: _docker/app/Dockerfile  # Вказуємо шлях до Dockerfile
        volumes:
        - ./:/var/www
        depends_on:
            - mysql_db
        container_name: news_app

    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: news
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql_db
            - PMA_USER=root
            - PMA_PASSWORD=root
